Fix bat rebuild script looking for the wrong executable

diff --git a/run_onchange_30-rebuild-bat-cache.sh.tmpl b/run_onchange_30-rebuild-bat-cache.sh.tmpl
--- a/run_onchange_30-rebuild-bat-cache.sh.tmpl
+++ b/run_onchange_30-rebuild-bat-cache.sh.tmpl
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
+set -euo pipefail
+# shellcheck source=tools/script_logging.sh
+. {{ joinPath .chezmoi.sourceDir "tools/script_logging.sh" }}
+script_start
 
 {{- range glob (joinPath .chezmoi.homeDir ".config/bat/**/*") }}
 # hash({{ . }}): {{ . | sha256sum }}
 {{- end }}
 
-{{- if isExecutable "bat" }}
-echo "Rebuilding bat cache"
+{{- if lookPath "bat" }}
+info "Rebuilding bat cache"
 bat cache --build
 {{- else }}
-echo "bat not found in PATH, skipping cache rebuild"
+warn "bat not found in PATH, skipping cache rebuild"
 {{- end }}
+
+script_end
